- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yaml   # the variables will be declaired in the vars.yaml file
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."