- name: variables from args
  hosts: localhost
  tasks:
  - name: get variables from command line args
    ansible.builtin.commands:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"

## the command should be
## ansible-playbook -i inventory -e ansible_user=ec2-user -e ansible_password=DevOps321 09-vars-args.yaml -e "PERSON=Ramesh WISHES=Morning"