- name: data-types
  hosts: localhost
  vars:
   Course: "DevOps with AWS"  # Key value pair
   Tools: # list
   - Linux
   - Docker
   - AWS
   Experience:  # map 
    DevOps: 3 # number  #&& in map we will have hey value
    AWS: 2
    Docker: 1
   RealProject: true # boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{RealProject}}"

# # Key value pair
# list
# map
# number
# boolean
